routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'home', 'uses' => 'Frontend\HomeController@index' ]);
Route::get('/nhom-bai-viet/{slug}', ['as' => 'article_category', 'uses' => 'Frontend\ArticleController@category' ]);
Route::get('/bai-viet/{slug}', ['as' => 'article_detail', 'uses' => 'Frontend\ArticleController@detail' ]);
Route::get('/nhom-san-pham/{slug}', ['as' => 'product_category', 'uses' => 'Frontend\ProductController@category' ]);
Route::get('/san-pham/{slug}', ['as' => 'product_detail', 'uses' => 'Frontend\ProductController@detail' ]);

app/Models/Product.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Cviebrock\EloquentSluggable\Sluggable;
use Cviebrock\EloquentSluggable\SluggableScopeHelpers;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use CrudTrait;
    use Sluggable, SluggableScopeHelpers;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'products';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];
    protected $casts = [
        'images' => 'array',
        'properties' => 'array',
    ];
    
    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_or_name',
            ],
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */
    
    public function product_category()
    {
        return $this->belongsTo(ProductCategory::class, 'product_category_id');
    }
    
    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'product_tag');
    }

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */
    
    // The slug is created automatically from the "name" field if no slug exists.
    public function getSlugOrNameAttribute()
    {
        if ($this->slug != '') {
            return $this->slug;
        }
        
        return $this->name;
    }
    
    public function getPriceFormattedAttribute(){
        return number_format($this->attributes['price']) . " VNĐ";
    }

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
    
    
}

app/Http/Controllers/Frontend/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: hocvt
 * Date: 2020-06-21
 * Time: 04:21
 */

namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\ArticleCategory;

class ArticleController extends Controller {
    
    public function category($slug){
        $category = ArticleCategory::findBySlugOrFail( $slug );
        
        \SEO::setTitle( $category->seo_title ?: $category->name );
        \SEO::setDescription( $category->seo_description ?: $category->name );
        
        return view('frontend.article_category', compact( 'category'));
    }
    public function detail($slug){
        $article = Article::findBySlugOrFail( $slug );
        $category = $article->article_category;
    
        \SEO::setTitle( $article->seo_title ?: $article->name );
        \SEO::setDescription( $article->seo_description ?: $article->name . " - " . $category->name );
    
        return view('frontend.article_detail', compact( 'article', 'category'));
    }
    
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        $new_products = Product::orderBy('id', 'desc')->take(12)->get();
        return view('frontend.home', compact( 'new_products'));
    }
}

app/Http/Controllers/Frontend/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: hocvt
 * Date: 2020-06-21
 * Time: 04:21
 */

namespace App\Http\Controllers\Frontend;


use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\ProductCategory;

class ProductController extends Controller {
    
    public function category($slug){
        
        $category = ProductCategory::findBySlugOrFail( $slug );
        
        \SEO::setTitle( $category->seo_title ?: $category->name );
        \SEO::setDescription( $category->seo_description ?: $category->name );
        
        return view('frontend.product_category', compact( 'category'));
    }
    public function detail($slug){
        $product = Product::findBySlugOrFail( $slug );
    
        \SEO::setTitle( $product->seo_title ?: $product->name );
        \SEO::setDescription( $product->seo_description ?: $product->name );
        
        $category = $product->product_category;
        return view('frontend.product_detail', compact( 'product', 'category'));
    }
    
}

resources/views/frontend/article_category.blade.php
@extends('layouts.master')



@section('content')

    <section class="bread-crumb mt-3">
        <div class="container">
            <div class="row">
                <div class="w-100">
                    <ul class="breadcrumb list-unstyled " vocab="http://schema.org/" typeof="BreadcrumbList">
                        <li class="home mr-2" property="itemListElement" typeof="ListItem">
                            <a property="item" href="/" typeof="WebPage" title="Về trang chủ">
                                <span property="name">Trang chủ</span>
                            </a>
                            <meta property="position" content="1">
                        </li>
                        <li class="mr-2" property="itemListElement" typeof="ListItem">
                            <a property="item" href="{{route('article_category', ['slug' => $category->slug])}}"
                               title="{{$category->name}}" typeof="WebPage">
                                >> <span property="name">{{$category->name}}</span>
                            </a>
                            <meta property="position" content="2">
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-2">

        <div class="row">
            <div class="col-md-8 col-lg-9 order-md-2">
                <div class="pl-md-2">
                    <div class="row">
                        <div class="category-intro p-1">
                            <h3 class="category-header">
                                Bài viết mục : {{$category->name}}
                            </h3>
                        </div>
                        <div class="card-products-slide mb-4">
                            @php($articles = $category->articles()->paginate(10))
                            <ul class="list-unstyled my-5 px-2">
                                @foreach($articles as $article)

                                    <li class="media py-2" style="height: 200px;border-bottom: 1px solid #cccccc;">
                                        <img class="mr-3" style="width: 200px;" src="{{url($article->image)}}"
                                             alt="{{$article->title}}">
                                        <div class="media-body">
                                            <h4 class="mt-0 mb-1">
                                                <a href="{{route('article_detail', ['slug' => $article->slug])}}">
                                                    {{$article->title}}
                                                </a></h4>
                                            <div class="text-muted py-2"><i class="fa fa-user"></i> Admin
                                                , {{$article->date}} </div>
                                            {!! \Illuminate\Support\Str::limit(strip_tags($article->content), 400) !!}
                                        </div>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-3 order-md-1">
                @include('partials.sidebar')
            </div>
        </div>

    </div>

@endsection


@push('after_scripts')
    <script>

      function applyOwl(slide_container, nav_container) {
        return $(slide_container).owlCarousel({
          loop: true,
          margin: 10,
          responsiveClass: true,
          responsive: {
            0: {
              items: 1,
              nav: true
            },
            600: {
              items: 3,
              nav: false
            },
            1000: {
              items: 4,
              nav: true,
              loop: false
            }
          },
          navContainer: nav_container,
          dots: false
        });
      }

      // $(document).ready(function(){
      //     applyOwl('#owl-carousel-1', '#owl-slide-nav-1');
      //     applyOwl('#owl-carousel-2', '#owl-slide-nav-2');
      //     applyOwl('#owl-carousel-3', '#owl-slide-nav-3');
      // });

    </script>
@endpush

resources/views/frontend/article_detail.blade.php
@extends('layouts.master')



@section('content')

    <section class="bread-crumb mt-3">
        <div class="container">
            <div class="row">
                <div class="w-100">
                    <ul class="breadcrumb list-unstyled " vocab="http://schema.org/" typeof="BreadcrumbList">
                        <li class="home mr-2" property="itemListElement" typeof="ListItem">
                            <a property="item" href="/" typeof="WebPage" title="Về trang chủ">
                                <span property="name">Trang chủ</span>
                            </a>
                            <meta property="position" content="1">
                        </li>
                        <li class="mr-2" property="itemListElement" typeof="ListItem">
                            <a property="item" href="{{route('article_category', ['slug' => $category->slug])}}"
                               title="{{$category->name}}" typeof="WebPage">
                                >> <span property="name">{{$category->name}}</span>
                            </a>
                            <meta property="position" content="2">
                        </li>
                        <li>
                            >> <span property="name">{{$article->title}}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-2">

        <div class="row">
            <div class="col-md-8 col-lg-9 order-md-2">
                <div class="pl-md-2">
                    <div class="row">
                        <div class="category-intro p-1">
                            <h3 class="category-header">
                                {{$article->title}}
                            </h3>
                            <div class="text-muted py-2"><i class="fa fa-user"></i> Admin
                                , {{$article->date}} </div>
                        </div>
                        <div class="card-products-slide mb-4 p-2 rft-wrapper bg-white">
                            {!! $article->content !!}
                            <p class="my-5">
                                <b>Tags : </b><br/>
                                @foreach($article->tags as $tag)
                                    <button type="button" class="btn btn-outline-primary">{{$tag->name}}</button>
                                @endforeach
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 col-lg-3 order-md-1">
                @include('partials.sidebar')
            </div>
        </div>

    </div>

@endsection


@push('after_scripts')
    <script>

      function applyOwl(slide_container, nav_container) {
        return $(slide_container).owlCarousel({
          loop: true,
          margin: 10,
          responsiveClass: true,
          responsive: {
            0: {
              items: 1,
              nav: true
            },
            600: {
              items: 3,
              nav: false
            },
            1000: {
              items: 4,
              nav: true,
              loop: false
            }
          },
          navContainer: nav_container,
          dots: false
        });
      }

      // $(document).ready(function(){
      //     applyOwl('#owl-carousel-1', '#owl-slide-nav-1');
      //     applyOwl('#owl-carousel-2', '#owl-slide-nav-2');
      //     applyOwl('#owl-carousel-3', '#owl-slide-nav-3');
      // });

    </script>
@endpush

resources/views/frontend/home.blade.php
@extends('layouts.master')



@section('content')

  @include('includes.home_slide')

  <div class="container">

    <div class="row">
      <div class="col-md-8 col-lg-9 order-md-2">
        <div class="pl-md-2">
          <div class="row">
            <div class="card-products-slide mb-4">
              <div class="card-header font-weight-bold">
                <i class="fa fa-shopping-cart"></i> SẢN PHẨM MỚI
                <div class="pull-right owl-slide-nav" id="owl-slide-nav-1"></div>
              </div>
              <div class="owl-carousel owl-theme" id="owl-carousel-1" data-nav-container="#owl-slide-nav-1">
                @foreach($new_products as $product)
                  <div class="item">
                    @include('includes.product-in-slide', compact('product'))
                  </div>
                @endforeach
              </div>
            </div>
            {{--<div class="card-products-slide mb-4">--}}
            {{--<div class="card-header font-weight-bold">--}}
            {{--<i class="fa fa-shopping-cart"></i> CHAI LỌ HŨ MỸ PHẨM CAO CẤP--}}
            {{--<div class="pull-right owl-slide-nav" id="owl-slide-nav-2" ></div>--}}
            {{--</div>--}}
            {{--<div class="owl-carousel owl-theme" id="owl-carousel-2" data-nav-container="#owl-slide-nav-2">--}}
            {{--<div class="item">--}}
            {{--@include('includes.product-in-slide')--}}
            {{--@include('includes.product-in-slide')--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--<div class="card-products-slide mb-4">--}}
            {{--<div class="card-header font-weight-bold">--}}
            {{--<i class="fa fa-shopping-cart"></i> CHAI LỌ HŨ MỸ PHẨM CAO CẤP--}}
            {{--<div class="pull-right owl-slide-nav" id="owl-slide-nav-3" ></div>--}}
            {{--</div>--}}
            {{--<div class="owl-carousel owl-theme" id="owl-carousel-3" data-nav-container="#owl-slide-nav-3">--}}
            {{--<div class="item">--}}
            {{--@include('includes.product-in-slide')--}}
            {{--</div>--}}
            {{--</div>--}}
            {{--</div>--}}
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-3 order-md-1">
        @include('partials.sidebar')
      </div>
    </div>

  </div>

@endsection


@push('after_scripts')
  <script>

      function applyOwl(slide_container, nav_container) {
          return $(slide_container).owlCarousel({
              loop: true,
              margin: 2,
              responsiveClass: true,
              responsive: {
                  0: {
                      items: 1,
                      nav: true
                  },
                  600: {
                      items: 3,
                      nav: false
                  },
                  1000: {
                      items: 4,
                      nav: true,
                      loop: false
                  }
              },
              navContainer: nav_container,
              dots: false
          });
      }

      $(document).ready(function () {
          applyOwl('#owl-carousel-1', '#owl-slide-nav-1');
          applyOwl('#owl-carousel-2', '#owl-slide-nav-2');
          applyOwl('#owl-carousel-3', '#owl-slide-nav-3');
      });

  </script>
@endpush

resources/views/frontend/product_category.blade.php
@extends('layouts.master')



@section('content')

  <section class="bread-crumb mt-3">
    <div class="container">
      <div class="row">
        <div class="w-100">
          <ul class="breadcrumb list-unstyled " vocab="http://schema.org/" typeof="BreadcrumbList">
            <li class="home mr-2" property="itemListElement" typeof="ListItem">
              <a property="item" href="/" typeof="WebPage" title="Về trang chủ">
                <span property="name">Trang chủ</span>
              </a>
              <meta property="position" content="1">
            </li>
            <li class="mr-2" property="itemListElement" typeof="ListItem">
              <a property="item" href="{{route('product_category', ['slug' => $category->slug])}}" title="{{$category->name}}" typeof="WebPage">
                >> <span property="name">{{$category->name}}</span>
              </a>
              <meta property="position" content="2">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <div class="container mt-2">

    <div class="row">
      <div class="col-md-8 col-lg-9 order-md-2">
        <div class="pl-md-2">
          <div class="row">
            <div class="category-intro p-1">
              <h3 class="category-header">
                {{$category->seo_title ?? $category->name}}
              </h3>
              <div class="category-description">
                <p>
                  {!! $category->introduction !!}
                </p>
              </div>
            </div>
            <div class="card-products-slide mb-4">
              <div class="card-header font-weight-bold">
                <i class="fa fa-shopping-cart"></i> {{$category->name}}
              </div>
              <div class="">
                <div class="row no-gutters">
                  @foreach($category->products as $product)
                  <div class="col-xl-3 col-lg-4 col-md-6">
                    @include('includes.product-in-slide', compact('product'))
                  </div>
                  @endforeach
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-3 order-md-1">
        @include('partials.sidebar')
      </div>
    </div>

  </div>

@endsection


@push('after_scripts')
  <script>

      function applyOwl(slide_container, nav_container){
          return $(slide_container).owlCarousel({
              loop:true,
              margin:10,
              responsiveClass:true,
              responsive:{
                  0:{
                      items:1,
                      nav:true
                  },
                  600:{
                      items:3,
                      nav:false
                  },
                  1000:{
                      items:4,
                      nav:true,
                      loop:false
                  }
              },
              navContainer: nav_container,
              dots: false
          });
      }

      // $(document).ready(function(){
      //     applyOwl('#owl-carousel-1', '#owl-slide-nav-1');
      //     applyOwl('#owl-carousel-2', '#owl-slide-nav-2');
      //     applyOwl('#owl-carousel-3', '#owl-slide-nav-3');
      // });

  </script>
@endpush

resources/views/frontend/product_detail.blade.php
@extends('layouts.master')



@section('content')
  <section class="bread-crumb mt-3">
    <div class="container">
      <div class="row">
        <div class="w-100">
          <ul class="breadcrumb list-unstyled " vocab="http://schema.org/" typeof="BreadcrumbList">
            <li class="home mr-2" property="itemListElement" typeof="ListItem">
              <a property="item" href="/" typeof="WebPage" title="Về trang chủ">
                <span property="name">Trang chủ</span>
              </a>
              <meta property="position" content="1">
            </li>
            <li class="mr-2" property="itemListElement" typeof="ListItem">
              <a property="item" href="{{route('product_category', ['slug' => $category->slug])}}" title="{{$category->name}}" typeof="WebPage">
                >> <span property="name">{{$category->name}}</span>
              </a>
              <meta property="position" content="2">
            </li>
            <li>
              >> <span property="name">{{$product->name}}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  <div class="container mt-2">

    <div class="row">
      <div class="col-md-8 col-lg-9 order-md-2">
        <div class="pl-md-2">
          <div class="row">
            <div class="product-detail col-md-6">
              <h3 class="mb-5">
                <a href="#">
                  {{$product->name}}
                </a>
              </h3>
              <p>
                <b>Thông tin sản phẩm : </b>
              </p>
              <div class="ml-2">
                <p>
                  + Mã sản phẩm : {{$product->code}}
                </p>
                @foreach($product->properties as $property)
                  @if(!empty($property['desc']) && !empty($property['name']))
                    <p>
                      + {{$property['name']}} : {{$property['desc']}}
                    </p>
                  @endif
                @endforeach
              </div>


              <p class="text-secondary mt-5" style="font-size: 150%;">
                Giá : <b>{{$product->price ? $product->price_formatted . " VNĐ" : "Liên hệ"}}</b>
              </p>
              <p>
                <b>Tags : </b><br/>
                @foreach($product->tags as $tag)
                  <button type="button" class="btn btn-outline-primary">{{$tag->name}}</button>
                @endforeach
              </p>

            </div>
            <div class="product-images col-md-6">
              <div style="min-height: 300px;width: 100%;">
                <div class="owl-carousel owl-theme" id="product-detail-images-slide">
                  @foreach($product->images as $image)
                    <img src="{{url($image)}}"/>
                  @endforeach
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="card-products-slide mb-4 mt-5">
              <div class="card-header font-weight-bold">
                <i class="fa fa-shopping-cart"></i> Mô tả chi tiết
              </div>
              <div class="col-12 my-5 product-detail-container rft-wrapper">
                {!! $product->detail !!}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="card-products-slide mb-4">
              <div class="card-header font-weight-bold">
                <i class="fa fa-shopping-cart"></i> Sản phẩm liên quan
              </div>
              <div class="">
                <div class="row no-gutters">
                  @foreach([1,2,3,4,5,6,7,8] as $i)
                    <div class="col-xl-3 col-lg-4 col-md-6">
                      @include('includes.product-in-slide')
                    </div>
                  @endforeach
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-4 col-lg-3 order-md-1">
        @include('partials.sidebar')
      </div>
    </div>

  </div>

@endsection


@push('after_scripts')
  <script>

      $('#product-detail-images-slide').owlCarousel({
          loop: true,
          margin: 10,
          nav: false,
          dots: true,
          items: 1
      })

  </script>
@endpush